### ISSUE TITLE
it's not clear where `RIOT_CLIENT_SECRET_ID` is to be created in the docs

### ISSUE THREAD

**Issue by pr-Mais** [trilleplay/rso-firebase-extension#1]
Hello! Thanks for submitting this extension for review.

I have a suggestion for `RIOT_CLIENT_SECRET_ID` param, as it's asking for an ID of a secret in the cloud, you could instead use the `secret` type and the extension will take care of creating the secret and allowing you to access it easily without using Secret Manager.

[Check here](https://firebase.google.com/docs/extensions/reference/extension-yaml#secret-params) for reference on the secret type.

```yaml
  - param: RIOT_CLIENT_SECRET
    label: Client Secret Location on Google Cloud Secret Manager.
    description: >-
      The Riot client secret.
    type: secret
    required: true
    immutable: true
```
